build:
	docker build -t pskreter/spawner:latest .

push:
	docker push pskreter/spawner:latest
	
run:
	docker run --rm --name spawner pskreter/spawner

rund:
	docker run --rm -d --name spawner pskreter/spawner